// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovclovxprwewvthaiglu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92Y2xvdnhwcndld3Z0aGFpZ2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjY2MzksImV4cCI6MjA2MDU0MjYzOX0.hhTlxWTxzj2qiJchuEc68O3z94dV5ZSHL2pRX-l7RxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);